/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

/**
 *
 * @author jhonz
 */
public class cargoEmbarcacion extends javax.swing.JPanel {

    /**
     * Creates new form cargoEmbarcacion
     */
    public cargoEmbarcacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelForm = new javax.swing.JPanel();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jLabelID1 = new javax.swing.JLabel();
        jLabelID2 = new javax.swing.JLabel();
        jLabelID3 = new javax.swing.JLabel();
        jTextFieldFecha1 = new javax.swing.JTextField();
        jTextFieldFecha2 = new javax.swing.JTextField();
        jTextFieldFecha3 = new javax.swing.JTextField();
        jLabelRegistroBodega = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabelEs = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jPanelForm.setBackground(new java.awt.Color(0, 51, 204));
        jPanelForm.setPreferredSize(new java.awt.Dimension(1200, 600));

        jTextFieldFecha.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFecha.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldFecha.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldFecha.setAutoscrolls(false);
        jTextFieldFecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldFecha.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextFieldFecha.setMinimumSize(new java.awt.Dimension(800, 18));
        jTextFieldFecha.setName(""); // NOI18N

        jLabelID.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID.setText("ID bodega:");
        jLabelID.setToolTipText("");

        jLabelID1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelID1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID1.setText("ID bodega:");
        jLabelID1.setToolTipText("");

        jLabelID2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelID2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID2.setText("ID bodega:");
        jLabelID2.setToolTipText("");

        jLabelID3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelID3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID3.setText("ID bodega:");
        jLabelID3.setToolTipText("");

        jTextFieldFecha1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFecha1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldFecha1.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldFecha1.setAutoscrolls(false);
        jTextFieldFecha1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldFecha1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextFieldFecha1.setMinimumSize(new java.awt.Dimension(800, 18));
        jTextFieldFecha1.setName(""); // NOI18N

        jTextFieldFecha2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFecha2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldFecha2.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldFecha2.setAutoscrolls(false);
        jTextFieldFecha2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldFecha2.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextFieldFecha2.setMinimumSize(new java.awt.Dimension(800, 18));
        jTextFieldFecha2.setName(""); // NOI18N

        jTextFieldFecha3.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFecha3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldFecha3.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldFecha3.setAutoscrolls(false);
        jTextFieldFecha3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldFecha3.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextFieldFecha3.setMinimumSize(new java.awt.Dimension(800, 18));
        jTextFieldFecha3.setName(""); // NOI18N

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jLabelID2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFecha3, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jLabelID1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jLabelID3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID1))
                .addGap(35, 35, 35)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelID)
                    .addComponent(jTextFieldFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID3)
                    .addComponent(jTextFieldFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID2)
                    .addComponent(jTextFieldFecha3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        add(jPanelForm, gridBagConstraints);

        jLabelRegistroBodega.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelRegistroBodega.setForeground(new java.awt.Color(0, 0, 0));
        jLabelRegistroBodega.setText("REGISTRAR BODEGA");
        jLabelRegistroBodega.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipady = 60;
        add(jLabelRegistroBodega, gridBagConstraints);

        jButtonGuardar.setBackground(new java.awt.Color(51, 102, 255));
        jButtonGuardar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setToolTipText("");
        jButtonGuardar.setBorder(null);
        jButtonGuardar.setBorderPainted(false);
        jButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonGuardar.setFocusPainted(false);
        jButtonGuardar.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jButtonGuardar, gridBagConstraints);

        jButtonEditar.setBackground(new java.awt.Color(51, 102, 255));
        jButtonEditar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.setToolTipText("");
        jButtonEditar.setBorder(null);
        jButtonEditar.setBorderPainted(false);
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonEditar.setFocusPainted(false);
        jButtonEditar.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(jButtonEditar, gridBagConstraints);

        jLabelEs.setText("jLabel1");
        jLabelEs.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipady = 20;
        add(jLabelEs, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabelEs;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelID1;
    private javax.swing.JLabel jLabelID2;
    private javax.swing.JLabel jLabelID3;
    private javax.swing.JLabel jLabelRegistroBodega;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldFecha1;
    private javax.swing.JTextField jTextFieldFecha2;
    private javax.swing.JTextField jTextFieldFecha3;
    // End of variables declaration//GEN-END:variables
}
