/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Danna Sofia
 */
public class InfoPuerto extends javax.swing.JPanel {

    private MarcoPrincipal principal;
    
    private String username, password;
    
        private static String PATH = "..\\ShippingControl\\data\\bodegas.csv";

    /**
     * Creates new form InfoPuerto
     */
    public InfoPuerto(MarcoPrincipal principal) {
        this.principal = principal;
        this.username=username;
        this.password=password;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoPuerto = new java.awt.Label();
        LabelNombre = new javax.swing.JLabel();
        LabelnBodegas = new javax.swing.JLabel();
        nombre = new java.awt.TextField();
        nBodegas = new java.awt.TextField();
        jButtonGuardar = new javax.swing.JButton();
        LabelcBodegas = new javax.swing.JLabel();
        cBodegas = new java.awt.TextField();

        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        InfoPuerto.setFont(new java.awt.Font("Trebuchet MS", 1, 60)); // NOI18N
        InfoPuerto.setText("Información del puerto");

        LabelNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        LabelNombre.setText("Nombre del puerto:");

        LabelnBodegas.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        LabelnBodegas.setText("Número de bodegas del puerto: ");
        LabelnBodegas.setToolTipText("");

        nombre.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        nombre.setPreferredSize(new java.awt.Dimension(93, 35));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        nBodegas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        nBodegas.setPreferredSize(new java.awt.Dimension(100, 35));
        nBodegas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBodegasActionPerformed(evt);
            }
        });

        jButtonGuardar.setBackground(new java.awt.Color(0, 51, 204));
        jButtonGuardar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setToolTipText("");
        jButtonGuardar.setBorder(null);
        jButtonGuardar.setBorderPainted(false);
        jButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonGuardar.setFocusPainted(false);
        jButtonGuardar.setPreferredSize(new java.awt.Dimension(100, 40));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        LabelcBodegas.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        LabelcBodegas.setText("Capacidad de bodegas del puerto: ");

        cBodegas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cBodegas.setPreferredSize(new java.awt.Dimension(100, 35));
        cBodegas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBodegasActionPerformed(evt);
            }
        });
        if(principal.getPrimerIngreso()){
            nombre.setEditable(true);
            nBodegas.setEditable(true);
            cBodegas.setEnabled(true);
            nombre.setBackground(new java.awt.Color(206, 218, 255));
            nBodegas.setBackground(new java.awt.Color(206, 218, 255));
            cBodegas.setBackground(new java.awt.Color(206, 218, 255));
        }else{
            nombre.setEditable(false);
            nombre.setText(Ingreso_usuario.getCredencialesPuerto()[2]);
            nBodegas.setEditable(false);
            nBodegas.setText(Ingreso_usuario.getCredencialesPuerto()[3]);
            cBodegas.setEditable(false);
            cBodegas.setText(Ingreso_usuario.getCredencialesPuerto()[4]);
            nombre.setBackground(new java.awt.Color(255, 255, 255));
            nBodegas.setBackground(new java.awt.Color(255, 255, 255));
            cBodegas.setBackground(new java.awt.Color(255,255,255));
            jButtonGuardar.setEnabled(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelnBodegas)
                                .addGap(26, 26, 26)
                                .addComponent(nBodegas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelNombre)
                                .addGap(42, 42, 42)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(InfoPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelcBodegas)
                                .addGap(26, 26, 26)
                                .addComponent(cBodegas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(538, 538, 538)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(InfoPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelnBodegas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nBodegas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cBodegas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelcBodegas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(408, 408, 408)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nBodegasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBodegasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nBodegasActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        if (nombre.getText().length() != 0 && nBodegas.getText().length() != 0) {
            Ingreso_usuario.Registro(nombre.getText(),nBodegas.getText(),cBodegas.getText());
            principal.habilitar(false);
            nombre.setEditable(false);
            nBodegas.setEditable(false);
            cBodegas.setEditable(false);
            nombre.setBackground(new java.awt.Color(255, 255, 255));
            nBodegas.setBackground(new java.awt.Color(255, 255, 255));
            cBodegas.setBackground(new java.awt.Color(255, 255, 255));
            jButtonGuardar.setEnabled(false);
            RegistrarBodegasCSV(Integer.valueOf(nBodegas.getText()), Integer.valueOf(cBodegas.getText()));
            principal.getPuerto().cargarBodegasCSV();
        } else {
            JOptionPane.showMessageDialog(null, "No se permiten espacios en blanco", "Atención", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonGuardarActionPerformed
    public static void RegistrarBodegasCSV(int n, int capacidad) {
        Random random = new Random();
        String zonas = "ABCDE";
        //char letter = zonas.charAt(random.nextInt(zonas.length()));
        try {
            new FileWriter(PATH, false).close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        try {
            for (long i = 0; i < n; i++) {
                FileWriter writeFile = new FileWriter(PATH, true);
                PrintWriter registrar = new PrintWriter(writeFile);
                registrar.println(String.valueOf(String.format("%03d", i)) + ","
                        + String.valueOf(capacidad) + ","
                        + "0" + ","
                        + zonas.charAt(random.nextInt(zonas.length())));
                registrar.close();
            }
        } catch (Exception e) {

        }
    }
    
    private void cBodegasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBodegasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBodegasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label InfoPuerto;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelcBodegas;
    private javax.swing.JLabel LabelnBodegas;
    private java.awt.TextField cBodegas;
    private javax.swing.JButton jButtonGuardar;
    private java.awt.TextField nBodegas;
    private java.awt.TextField nombre;
    // End of variables declaration//GEN-END:variables
}
