/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Danna Sofia
 */
public class InfoPuerto extends javax.swing.JPanel {

    private MarcoPrincipal principal;
    
    private String username, password;
    
        private static String PATH = "..\\ShippingControl\\data\\bodegas.csv";

    /**
     * Creates new form InfoPuerto
     */
    public InfoPuerto(MarcoPrincipal principal) {
        this.principal = principal;
        this.username=username;
        this.password=password;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelcBodegas = new javax.swing.JLabel();
        LabelnBodegas = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        nombre = new java.awt.TextField();
        nBodegas = new java.awt.TextField();
        cBodegas = new java.awt.TextField();
        jButtonGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelcBodegas.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        LabelcBodegas.setForeground(new java.awt.Color(0, 0, 0));
        LabelcBodegas.setText("Capacidad de bodegas del puerto: ");
        jPanel1.add(LabelcBodegas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 40));

        LabelnBodegas.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        LabelnBodegas.setForeground(new java.awt.Color(0, 0, 0));
        LabelnBodegas.setText("Número de bodegas del puerto: ");
        LabelnBodegas.setToolTipText("");
        jPanel1.add(LabelnBodegas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 40));

        LabelNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        LabelNombre.setForeground(new java.awt.Color(0, 0, 0));
        LabelNombre.setText("Nombre del puerto:");
        jPanel1.add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 40));

        nombre.setBackground(new java.awt.Color(204, 204, 204));
        nombre.setFont(new java.awt.Font("Trebuchet MS", 0, 22)); // NOI18N
        nombre.setPreferredSize(new java.awt.Dimension(93, 35));
        nombre.setSelectionStart(0);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 500, 40));

        nBodegas.setBackground(new java.awt.Color(204, 204, 204));
        nBodegas.setFont(new java.awt.Font("Trebuchet MS", 0, 22)); // NOI18N
        nBodegas.setPreferredSize(new java.awt.Dimension(100, 35));
        nBodegas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBodegasActionPerformed(evt);
            }
        });
        jPanel1.add(nBodegas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 500, 40));

        cBodegas.setBackground(new java.awt.Color(204, 204, 204));
        cBodegas.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        cBodegas.setPreferredSize(new java.awt.Dimension(100, 35));
        cBodegas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBodegasActionPerformed(evt);
            }
        });
        if(principal.getPrimerIngreso()){
            nombre.setEditable(true);
            nBodegas.setEditable(true);
            cBodegas.setEnabled(true);
            nombre.setBackground(new java.awt.Color(255, 255, 255));
            nBodegas.setBackground(new java.awt.Color(255, 255, 255));
            cBodegas.setBackground(new java.awt.Color(255, 255, 255));
        }else{
            nombre.setEditable(false);
            nombre.setText(Ingreso_usuario.getCredencialesPuerto()[2]);
            nBodegas.setEditable(false);
            nBodegas.setText(Ingreso_usuario.getCredencialesPuerto()[3]);
            cBodegas.setEditable(false);
            cBodegas.setText(Ingreso_usuario.getCredencialesPuerto()[4]);
            nombre.setBackground(new java.awt.Color(204, 204, 204));
            nBodegas.setBackground(new java.awt.Color(204, 204, 204));
            cBodegas.setBackground(new java.awt.Color(204, 204, 204));
            jButtonGuardar.setEnabled(false);
        }
        jPanel1.add(cBodegas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 500, 40));

        jButtonGuardar.setBackground(new java.awt.Color(0, 51, 204));
        jButtonGuardar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setToolTipText("");
        jButtonGuardar.setBorder(null);
        jButtonGuardar.setBorderPainted(false);
        jButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonGuardar.setFocusPainted(false);
        jButtonGuardar.setPreferredSize(new java.awt.Dimension(100, 40));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 200, 80));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(10, 30, 49));
        jLabel9.setText("jLabel9");
        java.awt.Image fondo= new javax.swing.ImageIcon("..\\ShippingControl\\src\\Interfaz\\images\\Puertos2.jpg").getImage();
        jLabel9.setIcon( new javax.swing.ImageIcon(fondo.getScaledInstance(596, 696, java.awt.Image.SCALE_SMOOTH)));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 596, 696));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 600, 700));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Información del Puerto");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void nBodegasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBodegasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nBodegasActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        if (nombre.getText().length() != 0 && nBodegas.getText().length() != 0) {
            Ingreso_usuario.Registro(nombre.getText(),nBodegas.getText(),cBodegas.getText());
            principal.habilitar(false);
            nombre.setEditable(false);
            nBodegas.setEditable(false);
            cBodegas.setEditable(false);
            nombre.setBackground(new java.awt.Color(204, 204, 204));
            nBodegas.setBackground(new java.awt.Color(204, 204, 204));
            cBodegas.setBackground(new java.awt.Color(204, 204, 204));
            jButtonGuardar.setEnabled(false);
            RegistrarBodegasCSV(Integer.valueOf(nBodegas.getText()), Integer.valueOf(cBodegas.getText()));
            principal.getPuerto().cargarBodegasCSV();
        } else {
            JOptionPane.showMessageDialog(null, "No se permiten espacios en blanco", "Atención", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonGuardarActionPerformed
    public static void RegistrarBodegasCSV(int n, int capacidad) {
        Random random = new Random();
        String zonas = "ABCDE";
        //char letter = zonas.charAt(random.nextInt(zonas.length()));
        try {
            new FileWriter(PATH, false).close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        try {
            for (long i = 0; i < n; i++) {
                FileWriter writeFile = new FileWriter(PATH, true);
                PrintWriter registrar = new PrintWriter(writeFile);
                registrar.println(String.valueOf(String.format("%03d", i)) + ","
                        + String.valueOf(capacidad) + ","
                        + "0" + ","
                        + zonas.charAt(random.nextInt(zonas.length())));
                registrar.close();
            }
        } catch (Exception e) {

        }
    }
    
    private void cBodegasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBodegasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBodegasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelcBodegas;
    private javax.swing.JLabel LabelnBodegas;
    private java.awt.TextField cBodegas;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.TextField nBodegas;
    private java.awt.TextField nombre;
    // End of variables declaration//GEN-END:variables
}
