/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonz
 */
public class InicioSesion extends javax.swing.JPanel {

    private VentanaPrincipal principal;

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion(VentanaPrincipal principal) {
        this.principal = principal;
        initComponents();
    }
    
    public int dar1(){
        return 2;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelInicioSesion = new javax.swing.JPanel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelUs = new javax.swing.JLabel();
        jTextFieldNombreDeUsuario = new javax.swing.JTextField();
        jToggleButtonVerContraseña = new javax.swing.JToggleButton();
        jButtonIniciarSesion = new javax.swing.JButton();
        jLabelUs1 = new javax.swing.JLabel();
        jPasswordFieldCon = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanelIrAReg = new javax.swing.JPanel();
        jLabelCr = new javax.swing.JLabel();
        jButtonIrARegistro = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanelInicioImage = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelImagenInicio = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jPanelInicioSesion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInicioSesion.setPreferredSize(new java.awt.Dimension(600, 800));
        jPanelInicioSesion.setLayout(new java.awt.GridBagLayout());

        jLabelInicio.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelInicio.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInicio.setText("INICIO DE SESIÓN");
        jLabelInicio.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelInicioSesion.add(jLabelInicio, gridBagConstraints);

        jLabelContraseña.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jLabelContraseña.setText("Contraseña");
        jLabelContraseña.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelInicioSesion.add(jLabelContraseña, gridBagConstraints);

        jLabelUs.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelUs.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUs.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelInicioSesion.add(jLabelUs, gridBagConstraints);

        jTextFieldNombreDeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombreDeUsuario.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldNombreDeUsuario.setForeground(new java.awt.Color(97, 97, 97));
        jTextFieldNombreDeUsuario.setAutoscrolls(false);
        jTextFieldNombreDeUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextFieldNombreDeUsuario.setPreferredSize(new java.awt.Dimension(500, 35));
        jTextFieldNombreDeUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNombreDeUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreDeUsuarioFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        jPanelInicioSesion.add(jTextFieldNombreDeUsuario, gridBagConstraints);

        jToggleButtonVerContraseña.setBackground(new java.awt.Color(0, 128, 255));
        jToggleButtonVerContraseña.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jToggleButtonVerContraseña.setForeground(new java.awt.Color(0, 0, 0));
        java.awt.Image img= new javax.swing.ImageIcon("..\\ShippingControl\\src\\Interfaz\\images\\ver.png").getImage();
        jToggleButtonVerContraseña.setIcon(new javax.swing.ImageIcon(img.getScaledInstance(27, 19, java.awt.Image.SCALE_SMOOTH)));
        jToggleButtonVerContraseña.setToolTipText("");
        jToggleButtonVerContraseña.setBorder(null);
        jToggleButtonVerContraseña.setContentAreaFilled(false);
        jToggleButtonVerContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonVerContraseña.setFocusPainted(false);
        jToggleButtonVerContraseña.setPreferredSize(new java.awt.Dimension(45, 32));
        img= new javax.swing.ImageIcon("..\\ShippingControl\\src\\Interfaz\\images\\noVer.png").getImage();
        jToggleButtonVerContraseña.setSelectedIcon(new javax.swing.ImageIcon(img.getScaledInstance(25, 17, java.awt.Image.SCALE_SMOOTH)));
        jToggleButtonVerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVerContraseñaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanelInicioSesion.add(jToggleButtonVerContraseña, gridBagConstraints);

        jButtonIniciarSesion.setBackground(new java.awt.Color(0, 51, 204));
        jButtonIniciarSesion.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButtonIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciarSesion.setText("Iniciar sesión");
        jButtonIniciarSesion.setToolTipText("");
        jButtonIniciarSesion.setBorder(null);
        jButtonIniciarSesion.setBorderPainted(false);
        jButtonIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonIniciarSesion.setFocusPainted(false);
        jButtonIniciarSesion.setPreferredSize(new java.awt.Dimension(400, 40));
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanelInicioSesion.add(jButtonIniciarSesion, gridBagConstraints);

        jLabelUs1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelUs1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUs1.setText("Nombre de usuario");
        jLabelUs1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelInicioSesion.add(jLabelUs1, gridBagConstraints);

        jPasswordFieldCon.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldCon.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPasswordFieldCon.setToolTipText("");
        jPasswordFieldCon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPasswordFieldCon.setPreferredSize(new java.awt.Dimension(500, 35));
        jPasswordFieldCon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldConFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldConFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        jPanelInicioSesion.add(jPasswordFieldCon, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 2;
        jPanelInicioSesion.add(jPanel1, gridBagConstraints);

        jPanelIrAReg.setBackground(new java.awt.Color(255, 255, 255));
        jPanelIrAReg.setLayout(new java.awt.GridBagLayout());

        jLabelCr.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelCr.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCr.setText("¿No tienes cuenta?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelIrAReg.add(jLabelCr, gridBagConstraints);

        jButtonIrARegistro.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonIrARegistro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonIrARegistro.setText("Crear");
        jButtonIrARegistro.setBorder(null);
        jButtonIrARegistro.setBorderPainted(false);
        jButtonIrARegistro.setContentAreaFilled(false);
        jButtonIrARegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIrARegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonIrARegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonIrARegistroMouseExited(evt);
            }
        });
        jButtonIrARegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrARegistroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanelIrAReg.add(jButtonIrARegistro, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 15;
        jPanelInicioSesion.add(jPanelIrAReg, gridBagConstraints);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 2;
        jPanelInicioSesion.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jPanelInicioSesion, gridBagConstraints);

        jPanelInicioImage.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInicioImage.setPreferredSize(new java.awt.Dimension(600, 800));
        jPanelInicioImage.setVerifyInputWhenFocusTarget(false);
        jPanelInicioImage.setLayout(new java.awt.GridBagLayout());

        img= new javax.swing.ImageIcon("..\\ShippingControl\\src\\Interfaz\\images\\LogoShippingControl.png").getImage();
        jLabelLogo.setIcon(new javax.swing.ImageIcon(img.getScaledInstance(468, 210, java.awt.Image.SCALE_SMOOTH)));
        jLabelLogo.setText("LOGO");
        jLabelLogo.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanelInicioImage.add(jLabelLogo, gridBagConstraints);

        jLabelImagenInicio.setBackground(new java.awt.Color(255, 0, 51));
        jLabelImagenInicio.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        java.awt.Image fondo= new javax.swing.ImageIcon("..\\ShippingControl\\src\\Interfaz\\images\\puerto.jpg").getImage();
        jLabelImagenInicio.setIcon( new javax.swing.ImageIcon(fondo.getScaledInstance(600, 800, java.awt.Image.SCALE_SMOOTH)));
        jLabelImagenInicio.setToolTipText("");
        jLabelImagenInicio.setPreferredSize(new java.awt.Dimension(600, 800));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 20);
        jPanelInicioImage.add(jLabelImagenInicio, gridBagConstraints);

        add(jPanelInicioImage, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreDeUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreDeUsuarioFocusGained
        // TODO add your handling code here:
        jTextFieldNombreDeUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 204)));
    }//GEN-LAST:event_jTextFieldNombreDeUsuarioFocusGained

    private void jTextFieldNombreDeUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreDeUsuarioFocusLost
        // TODO add your handling code here:
        jTextFieldNombreDeUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jTextFieldNombreDeUsuarioFocusLost

    private void jToggleButtonVerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVerContraseñaActionPerformed
        // TODO add your handling code here:
        if (jToggleButtonVerContraseña.isSelected()) {
            jPasswordFieldCon.setEchoChar((char) 0);
        } else {
            jPasswordFieldCon.setEchoChar('*');
        }
    }//GEN-LAST:event_jToggleButtonVerContraseñaActionPerformed

    private void jPasswordFieldConFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldConFocusGained
        // TODO add your handling code here:
        jPasswordFieldCon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 204)));

    }//GEN-LAST:event_jPasswordFieldConFocusGained

    private void jPasswordFieldConFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldConFocusLost
        // TODO add your handling code here:
        jPasswordFieldCon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jPasswordFieldConFocusLost

    private void jButtonIrARegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrARegistroActionPerformed
        // TODO add your handling code here:
        principal.addPanelRegistro();
    }//GEN-LAST:event_jButtonIrARegistroActionPerformed

    private void jButtonIrARegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIrARegistroMouseEntered
        // TODO add your handling code here:
        jButtonIrARegistro.setForeground(new java.awt.Color(0, 51, 204));
    }//GEN-LAST:event_jButtonIrARegistroMouseEntered

    private void jButtonIrARegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIrARegistroMouseExited
        // TODO add your handling code here:
        jButtonIrARegistro.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButtonIrARegistroMouseExited

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        // TODO add your handling code here:
        if (Ingreso_usuario.Ingreso(jTextFieldNombreDeUsuario.getText(), String.valueOf(jPasswordFieldCon.getPassword()))) {
            Ingreso_usuario.setCredenciales(jTextFieldNombreDeUsuario.getText(), String.valueOf(jPasswordFieldCon.getPassword()));
            principal.addMarcoPrincipal(false);
        } else {
            JOptionPane.showMessageDialog(null, "El usuario no ha sido encontrado, revise las credenciales", "Atención", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JButton jButtonIrARegistro;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelCr;
    private javax.swing.JLabel jLabelImagenInicio;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelUs;
    private javax.swing.JLabel jLabelUs1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelInicioImage;
    private javax.swing.JPanel jPanelInicioSesion;
    private javax.swing.JPanel jPanelIrAReg;
    private javax.swing.JPasswordField jPasswordFieldCon;
    private javax.swing.JTextField jTextFieldNombreDeUsuario;
    private javax.swing.JToggleButton jToggleButtonVerContraseña;
    // End of variables declaration//GEN-END:variables
}
