/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Mundo.estructuras.listas.LinkedList;
import Mundo.estructuras.listas.Node;
import Mundo.shippingcontrol.Embarcacion;

public class RegistroEmbarcacion extends javax.swing.JPanel {

    /**
     * Creates new form RegistroEmbarcacionForm
     */
    MarcoPrincipal principal;

    private String[] datos = new String[7];

    private boolean registro;

    public RegistroEmbarcacion(boolean registro, MarcoPrincipal principal, int IMO, String nombre, String bandera, int tipo, int capacidad, int actual, boolean disp) {
        this.registro = registro;
        this.principal = principal;
        datos[0] = String.valueOf(IMO);
        datos[1] = nombre;
        datos[2] = bandera;
        datos[3] = String.valueOf(tipo);
        datos[4] = String.valueOf(capacidad);
        datos[5] = String.valueOf(actual);
        datos[6] = String.valueOf(disp);
        initComponents();
        habilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IMO = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        bandera = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        capacidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        contenedores = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jComboBoxDisp = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButtonGuardarRegistro = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1200, 800));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 60)); // NOI18N
        jLabel1.setText("Embarcación");

        IMO.setEditable(false);
        IMO.setBackground(new java.awt.Color(255, 255, 255));
        IMO.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        IMO.setPreferredSize(new java.awt.Dimension(80, 35));
        IMO.setText(datos[0]);

        nombre.setEditable(false);
        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        nombre.setPreferredSize(new java.awt.Dimension(80, 35));
        nombre.setText(datos[1]);

        bandera.setEditable(false);
        bandera.setBackground(new java.awt.Color(255, 255, 255));
        bandera.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bandera.setPreferredSize(new java.awt.Dimension(80, 35));
        bandera.setText(datos[2]);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("IMO: ");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Nombre de embarcación:");

        capacidad.setEditable(false);
        capacidad.setBackground(new java.awt.Color(255, 255, 255));
        capacidad.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        capacidad.setToolTipText("");
        capacidad.setPreferredSize(new java.awt.Dimension(197, 35));
        capacidad.setText(datos[4]);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("Bandera:");

        contenedores.setEditable(false);
        contenedores.setBackground(new java.awt.Color(255, 255, 255));
        contenedores.setPreferredSize(new java.awt.Dimension(228, 35));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Tipo de embarcación:");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("Capacidad de contenedores:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("Número actual de contenedores:");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setText("Disponibilidad:");

        jComboBoxTipo.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cargo general", "Portacontenedor", "Granelero", "Frigorifrico", "Ro-Ro", "Tanquero", "Industrial" }));
        jComboBoxTipo.setEnabled(false);
        jComboBoxTipo.setPreferredSize(new java.awt.Dimension(90, 35));
        jComboBoxTipo.setSelectedIndex(Integer.valueOf(datos[3]));

        jComboBoxDisp.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxDisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));
        jComboBoxDisp.setSelectedIndex(1);
        jComboBoxDisp.setEnabled(false);
        jComboBoxDisp.setPreferredSize(new java.awt.Dimension(90, 35));
        if(datos[6]=="true"){
            jComboBoxDisp.setSelectedIndex(1);
        }else{
            jComboBoxDisp.setSelectedIndex(0);
        }

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonGuardarRegistro.setBackground(new java.awt.Color(0, 51, 204));
        jButtonGuardarRegistro.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButtonGuardarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardarRegistro.setText("Registrar");
        jButtonGuardarRegistro.setToolTipText("");
        jButtonGuardarRegistro.setBorder(null);
        jButtonGuardarRegistro.setBorderPainted(false);
        jButtonGuardarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonGuardarRegistro.setFocusPainted(false);
        jButtonGuardarRegistro.setPreferredSize(new java.awt.Dimension(100, 40));
        jButtonGuardarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 160, 60));

        jButtonGuardar.setBackground(new java.awt.Color(0, 51, 204));
        jButtonGuardar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setToolTipText("");
        jButtonGuardar.setBorder(null);
        jButtonGuardar.setBorderPainted(false);
        jButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonGuardar.setFocusPainted(false);
        jButtonGuardar.setPreferredSize(new java.awt.Dimension(100, 40));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 160, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(contenedores, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bandera, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IMO, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxDisp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(477, 477, 477))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bandera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contenedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        contenedores.setText(datos[5]);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        principal.addPanel(1, new MenuEmbarcaciones(principal));
        LinkedList<Embarcacion> lista = principal.getPuerto().GetEmbarcaciones();
        Node<Embarcacion> Iterador = lista.getBeginNode();
        while (Iterador != null) {
            if (Iterador.getData().getIMO() == Integer.valueOf(IMO.getText())) {
                Iterador.getData().setActuales(Integer.valueOf(contenedores.getText()));
                Iterador.getData().setDisponibilidad((jComboBoxDisp.getSelectedIndex() == 0) ? false : true);
                System.out.println(Boolean.valueOf(String.valueOf(jComboBoxDisp.getSelectedIndex())));
            }
            Iterador = Iterador.nextNode;
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonGuardarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarRegistroActionPerformed
        // TODO add your handling code here:
        Node<Embarcacion> node=new Node<Embarcacion>(new Embarcacion(Integer.parseInt(IMO.getText()),nombre.getText(),bandera.getText(),
                jComboBoxTipo.getSelectedIndex(),Integer.valueOf(capacidad.getText()),Integer.valueOf(contenedores.getText()),
        (jComboBoxDisp.getSelectedIndex() == 0) ? false : true));
        principal.getPuerto().GetEmbarcaciones().Enqueue(node);
        principal.addPanel(1, new MenuEmbarcaciones(principal));
    }//GEN-LAST:event_jButtonGuardarRegistroActionPerformed
    private void habilitar() {
        if (registro) {
            nombre.setEditable(true);
            bandera.setEditable(true);
            jComboBoxTipo.setEnabled(true);
            contenedores.setEditable(true);
            capacidad.setEditable(true);
            jComboBoxDisp.setEnabled(true);
            nombre.setBackground(new java.awt.Color(206, 218, 255));
            bandera.setBackground(new java.awt.Color(206, 218, 255));
            jComboBoxTipo.setBackground(new java.awt.Color(206, 218, 255));
            capacidad.setBackground(new java.awt.Color(206, 218, 255));
            contenedores.setBackground(new java.awt.Color(206, 218, 255));
            jComboBoxDisp.setBackground(new java.awt.Color(206, 218, 255));
            jButtonGuardar.setVisible(false);
            jButtonGuardarRegistro.setVisible(true);
        } else {
            nombre.setEditable(false);
            bandera.setEditable(false);
            jComboBoxTipo.setEnabled(false);
            contenedores.setEditable(true);
            capacidad.setEditable(false);
            jComboBoxDisp.setEnabled(true);
            nombre.setBackground(new java.awt.Color(255, 255, 255));
            bandera.setBackground(new java.awt.Color(255, 255, 255));
            jComboBoxTipo.setBackground(new java.awt.Color(255, 255, 255));
            capacidad.setBackground(new java.awt.Color(255, 255, 255));
            contenedores.setBackground(new java.awt.Color(206, 218, 255));
            jComboBoxDisp.setBackground(new java.awt.Color(206, 218, 255));
            jButtonGuardar.setVisible(true);
            jButtonGuardarRegistro.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IMO;
    private javax.swing.JTextField bandera;
    private javax.swing.JTextField capacidad;
    private javax.swing.JTextField contenedores;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonGuardarRegistro;
    private javax.swing.JComboBox<String> jComboBoxDisp;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables

}
